apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: jimmy
subjects:
- kind: ServiceAccount
  name: jimmy-serviceaccount
  namespace: jimmy
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

