apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  labels:
    app: nginx
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: nginx
    release: {{ .Release.Name }}

